[platformio]
src_dir = main
default_envs = esp32

[env:esp32]
platform = platformio/espressif32@6.13.0
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.sdkconfig_defaults = sdkconfig.defaults
build_unflags = -Os
build_flags = -O3

[env:esp32s3]
platform = platformio/espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.sdkconfig_defaults = sdkconfig.s3.defaults
